apiVersion: v1
kind: Service
metadata:
  name: url-shortener-service
spec:
  type: LoadBalancer  # Use NodePort if you're using Minikube
  ports:
  - port: 80
    targetPort: 5000  # Must match your app's port
  selector:
    app: url-shortener